{% set name = "onnxscript" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/onnxscript-{{ version }}.tar.gz
  sha256: 60820d4c3e39f8ea7d945dd4f96fa5dd23c3c2e111022512477c52c9e78eb3d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.0.0
    - pip
  run:
    - python >={{ python_min }}
    - ml_dtypes
    - numpy
    - onnx-ir >=0.1.3,<2
    - onnx >=1.16
    - packaging
    - typing_extensions >=4.10

test:
  imports:
    - onnxscript
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/onnxscript
  summary: Naturally author ONNX functions and models using a subset of Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
